import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased m-4`}
      >
        <div className="flex flex-col">
          <div className="navbar bg-neutral text-neutral-content mb-4">
            <div className="flex-1">
              <a className="btn btn-ghost text-xl uppercase">SHADCN</a>
            </div>
        
          </div>        

        </div>
        {children}
      </body>
    </html>
  );
}
