#!/usr/bin/env just --justfile
# ^ A shebang isn't required, but allows a justfile to be executed
#   like a script, with `./justfile test`, for example.

set dotenv-load := true

# default lists actions
default:
  @just -f {{ source_file() }} --list

backend-start:
  #!/usr/bin/env bash
  set -eufo pipefail

  cd ./backend
  just run start:dev

frontend-start:
  #!/usr/bin/env bash
  set -eufo pipefail

  cd ./frontend
  just run dev