import 'bootstrap/dist/css/bootstrap.css'
import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from './blobs.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Blobs() {

  return (
    <>
      <Head>
        <title>Blobs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.overlay}>
          <div className={styles.text}>Hello World</div>
          <div className={`${styles.message} ${styles.blobs}`}></div>
      </div>
    </>
  )
}
