import 'bootstrap/dist/css/bootstrap.css'
import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from './blur.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Blur() {

  return (
    <>
      <Head>
        <title>Blur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>This is in the background</p>  
      <div className={styles.overlay}>
        <p className={`${styles.message} ${styles.title}`}><span>H</span><span>e</span><span>l</span><span>l</span><span>o</span><span>&nbsp;</span><span>W</span><span>o</span><span>r</span><span>l</span><span>d</span></p>

      </div>
    </>
  )
}
