import 'bootstrap/dist/css/bootstrap.css'
import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from './bouncy-text.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function BouncyText() {

  return (
    <>
      <Head>
        <title>Bouncy Text</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>This is in the background</p>  
      <div className={styles.overlay}>
        <div className={styles.page}>
          <p className={`${styles.message} ${styles.title1}`}>Hello World</p>

          <p className={`${styles.message} ${styles.title2}`}>Bouncy Text</p>

          <p className={`${styles.message} ${styles.title3}`}>Intro</p>
        </div>
      </div>
    </>
  )
}
