import 'bootstrap/dist/css/bootstrap.css'
import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from './letter-by-letter.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function LetterByLetter() {

  return (
    <>
      <Head>
        <title>Letter by Letter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>This is in the background</p>  
      <div className={styles.overlay}>
        <div className={styles.page}>
          <p className={`${styles.message} ${styles.title} ${styles.span}`}><span>H</span><span>e</span><span>l</span><span>l</span><span>o</span><span>&nbsp;</span><span>W</span><span>o</span><span>r</span><span>l</span><span>d</span></p>
        </div>
      </div>
    </>
  )
}
