import 'bootstrap/dist/css/bootstrap.css'
import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from './xor.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Xor() {

  return (
    <>
      <Head>
        <title>XOR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>This is in the background</p>  
      <div className={styles.overlay}>
        <div className={styles.page}>
          <div className={styles.text}>Hello World</div>
          <div className={styles.box}></div>
        </div>
      </div>
    </>
  )
}
