import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Blob from '../components/blob'
import Footer from '../components/footer'
import NavBar from '../components/navbar'
import Card from '../components/card'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const cards = [ 
    {
      src:"images/bouncytext_resize.png",
      title: "Bouncy-Zoom",
      description: "A nice little zoom bounce in and fade out example",
    },
    {
      src:"images/letterbyletter_resize.png",
      title: "Letter-by-Letter",
      description: "Same as the bouncy zoom, but with a delay on the fade of some letters",
    },
    {
      src:"images/xor_resize.png",
      title: "XOR",
      description: "A simple XOR overlay",
    },
    {
      src:"images/blur_resize.png",
      title: "Blur",
      description: "Uses a blur out effect to remove text",
    },
    {
      src:"images/blobs_resize.png",
      title: "Blobs",
      description: "Similar to the XOR effect but uses a blob",
    },
    {
      src:"images/plasma.png",
      title: "Plasma",
      description: "Plasma text effect",
    }
  ]

  return (
    <>
      <Head>
        <title>Text Effects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Blob />
      <div className={styles.overlay} >
        <NavBar/>
        <div className="container-fluid">
          <div className="row">
            <Card { ...cards[0] } />
            <Card { ...cards[1] } />
            <Card { ...cards[2] } />
          </div>
          <div className="row">
            <Card { ...cards[3] } />
            <Card { ...cards[4] } />
            <Card { ...cards[5] } />
          </div>
        </div>        
      </div>   
      <Footer />
    </>
  )
}
