import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Blob from '../components/blob'
import Footer from '../components/footer'
import NavBar from '../components/navbar'
import Card from '../components/card'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Text Effects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Blob />
      <div className={styles.overlay} >
        <NavBar/>
        <div className="container-fluid">
          <div className="row">
            <Card />
            <Card />
            <Card />
          </div>
          <div className="row">
            <Card />
            <Card />
            <Card />
          </div>
          <div className="row">
            <Card />
            <Card />
            <Card />
          </div>
        </div>        
      </div>   
      <Footer />
    </>
  )
}
