import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import TestCard from '../components/testcard'
import NavBar from '../components/navbar'
import ToolBar from '../components/toolbar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Testcard Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <ToolBar />


      <div>A test card, also known as a test pattern or calibration card, is a pattern of images and colors used to adjust and test the settings and performance of a television or video display system. It is typically used to align the brightness, contrast, color balance, and other settings to produce a clear and accurate picture. Test cards often include a series of patterns, such as bars, grids, and color swatches, that help technicians and users to adjust the display settings.
      </div>

    </>
  )
}
